apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api-deployment
  labels:
    app.kubernetes.io/name: fastapi-mongo
    app.kubernetes.io/instance: mongo-api
    app.kubernetes.io/part-of: mongo-loader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-mongo
        app.kubernetes.io/instance: mongo-api
        app.kubernetes.io/part-of: mongo-loader-app
    spec:
      containers:
        - name: fastapi-container
          image: "docker.io/YOUR_DOCKERHUB_USERNAME/fastapi-mongo-crud:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo-db-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config
                  key: MONGO_DB_NAME
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config
                  key: MONGO_COLLECTION_NAME
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"